---
title: "test"
author: "me"
date: "May 4, 2016"
output:
  html_document:
    number_sections: yes
    toc: yes
---

Libraries.

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(langcog)
theme_set(theme_bw())
```

Data. 

```{r}
d <- read_delim("data_expt1.txt", delim = " ") %>%
  filter(type == "real")

sim <- read_delim("SemSim_data1.txt", delim = " ") %>%
  filter(type == "real")
```

Plot

```{r}
ggplot(d, aes(x = sound_dist, y = answer, col = factor(concept_dist))) + 
  geom_jitter() + 
  geom_smooth()
```

Plot Similarity

```{r}
ggplot(sim, aes(x = distance, y = rating)) + 
  geom_jitter() + 
  geom_smooth()
```

Of means. 

```{r}
ms <- d %>%
  group_by(condition, sound_dist, concept_dist) %>%
  multi_boot_standard(col="answer")

ggplot(ms, aes(x = sound_dist, y = mean, col = factor(concept_dist))) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_line() + 
  facet_grid(.~condition)
```

Of means (similarity).
```{r}
mSim <- sim %>%
  group_by(concept1, concept2, distance) %>%
  multi_boot_standard(col="rating") %>%
  filter(concept1=="cow")

ggplot(mSim, aes(x = distance, y = mean)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) +
  geom_abline(slope = 2, lty = 2)
```

Now break out by conditions. 

```{r}
sounds <- d %>%
  filter(condition == "sound") %>%
  group_by(sound_dist) %>%
  multi_boot_standard(col = "answer")

concepts <- d %>%
  filter(condition == "concept") %>%
  group_by(concept_dist) %>%
  multi_boot_standard(col = "answer")

joint <- d %>%
  filter(condition == "joint") %>%
  group_by(concept_dist, sound_dist) %>%
  multi_boot_standard(col = "answer")

ggplot(joint, 
       aes(x = sound_dist, y = mean, col = factor(concept_dist))) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_line(lty = 2) + 
  geom_line(data = sounds, aes(col = 1), col = "black") + 
  geom_pointrange(data = sounds, aes(ymin = ci_lower, ymax = ci_upper, 
                                     col = 1), col = "black")

ggplot(joint, 
       aes(x = concept_dist, y = mean, col = factor(sound_dist))) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_line(lty = 2) + 
  geom_line(data = concepts, aes(col = 1), col = "black") + 
  geom_pointrange(data = concepts, aes(ymin = ci_lower, ymax = ci_upper, 
                                     col = 1), col = "black") + 
  scale_colour_solarized() 

```

```{r}
opt_combine <- 
  function (x,y) {
   1/(1 + (1/x-1) * (1/y-1))
  }

ms_all <- joint %>% 
  rename(joint = mean) %>%
  left_join(select(concepts, concept_dist, mean) %>% 
              rename(concepts = mean)) %>%
  left_join(select(sounds, sound_dist, mean) %>% 
              rename(sounds = mean)) %>%
  mutate(joint_pred = opt_combine(concepts, sounds)) %>%
  gather(model, pred, concepts, sounds, joint_pred)

ggplot(ms_all, 
       aes(x = pred, y = joint, col = factor(concept_dist), 
           shape = factor(sound_dist))) +
 geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_abline(slope = 1, lty = 2) + 
  facet_grid(.~model)

```
