---
title: "test"
date: "May 4, 2016"
output:
  html_document:
    number_sections: yes
    toc: yes
---

Libraries.

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(langcog)
theme_set(theme_bw())
```

Data. 

```{r}
d <- read_delim("noise_pilot3.txt", delim = " ") %>%
  filter(type == "real")
```


Plots of means. 

```{r}
ms <- d %>%
  group_by(condition, sound_dist) %>%
  multi_boot_standard(col="answer")

ggplot(ms, aes(x = sound_dist, y = mean)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_line() + 
  facet_grid(.~condition)
```


Now break out by conditions. 

```{r}

joint <- d %>%
  filter(condition == "joint") %>%
  group_by(concept_dist, sound_dist) %>%
  multi_boot_standard(col = "answer")

ggplot(joint, 
       aes(x = sound_dist, y = mean, col = factor(concept_dist))) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_line(lty = 2) 

ggplot(joint, 
       aes(x = concept_dist, y = mean, col = factor(sound_dist))) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_line(lty = 2) 

```

```{r}


#ms_all <- joint %>% 
#  rename(joint = mean) %>%
#  left_join(select(concepts, concept_dist, mean) %>% 
#              rename(concepts = mean)) %>%
#  left_join(select(sounds, sound_dist, mean) %>% 
#              rename(sounds = mean)) %>%
#  mutate(product = opt_combine(concepts, sounds)) %>%
#  mutate(regression = sum_combine(concepts, sounds)) %>%
#  gather(model, pred, concepts, sounds, product, regression)

#ggplot(ms_all, 
#       aes(x = pred, y = joint, col = factor(concept_dist), 
#           shape = factor(sound_dist))) +
# geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
#                  position = position_dodge(width = .1)) + 
#  geom_abline(slope = 1, lty = 2) + 
#  facet_grid(model~.)

```

```{r}
entropy <- function(p) {
  -p*log2(p)-(1-p)*log2(1-p)
}

#noisy <- joint %>% 
 # rename(joint = mean) %>%
#  left_join(select(concepts, concept_dist, mean) %>% 
#              rename(concepts = mean)) %>%
#  left_join(select(sounds, sound_dist, mean) %>% 
#              rename(sounds = mean)) %>%
#  mutate(joint_pred = opt_combine(concepts, sounds)) %>%
#  mutate(sound_entropy=entropy(sounds)) %>%
#  mutate(concept_entropy=entropy(concepts))
#ent <- noisy %>%
#  group_by(sound_dist) %>%
#  mutate(sensitivity=joint[concept_dist==4]-joint[concept_dist==1])

#ggplot(noisy,
#       aes(x = sound_entropy, y = joint, col = factor(concept_dist))) +
# geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
#                  position = position_dodge(width = .1)) 

#ggplot(ent,
#       aes(x = sound_entropy, y = sensitivity)) +
# geom_point()+geom_line()+scale_y_continuous(limits = c(0.15,0.3))



```