---
title: "test"
author: "me"
date: "May 4, 2016"
output:
  html_document:
    number_sections: yes
    toc: yes
---

Libraries.

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(langcog)
theme_set(theme_bw())
```

Data. 

```{r}
d <- read_delim("kids_pilot1_res.txt", delim = " ") %>%
  filter(type == "real")
```


Plots of means. 

```{r}
ms <- d %>%
  group_by(condition, sound_dist, concept_dist) %>%
  multi_boot_standard(col="answer")

ggplot(ms, aes(x = sound_dist, y = mean, col = factor(concept_dist))) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_line() + 
  facet_grid(.~condition)
```


Now break out by conditions. 

```{r}
sounds <- d %>%
  filter(condition == "sound") %>%
  group_by(sound_dist) %>%
  multi_boot_standard(col = "answer")

concepts <- d %>%
  filter(condition == "concept") %>%
  group_by(concept_dist) %>%
  multi_boot_standard(col = "answer")

joint <- d %>%
  filter(condition == "joint") %>%
  group_by(concept_dist, sound_dist) %>%
  multi_boot_standard(col = "answer")

ggplot(sounds, 
       aes(x = sound_dist, y = mean))  + geom_point()+geom_line()
      
ggplot(concepts, 
       aes(x = concept_dist, y = mean))  + geom_point()+geom_line()

ggplot(joint, 
       aes(x = sound_dist, y = mean, col = factor(concept_dist))) + 
  geom_point() + 
  geom_point(data = sounds, aes(col = 1), col = "black") +
  scale_colour_solarized() 

```

cues combination
```{r}
opt_combine <- function (x,y) {
   1/(1 + (1/x-1) * (1/y-1))
}

sum_combine <- function (x,y) {
   0.33*x+0.66*y
  }

ms_all <- joint %>% 
  rename(joint = mean) %>%
  left_join(select(concepts, concept_dist, mean) %>% 
              rename(concepts = mean)) %>%
  left_join(select(sounds, sound_dist, mean) %>% 
              rename(sounds = mean)) %>%
  mutate(product = opt_combine(concepts, sounds)) %>%
  mutate(regression = sum_combine(concepts, sounds)) %>%
  gather(model, pred, concepts, sounds, product, regression)

ggplot(ms_all, 
       aes(x = pred, y = joint, col = factor(concept_dist), 
           shape = factor(sound_dist))) +
 geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  geom_abline(slope = 1, lty = 2) + 
  facet_grid(model~.)

```
